version: "3.8"

# Additional Services - Overseerr, Stash, Cleanuparr, Huntarr
services:
  # Overseerr - Media request management with Cloudflare Tunnel
  overseerr:
    image: lscr.io/linuxserver/overseerr:${OVERSEERR_VERSION:-latest}
    container_name: overseerr
    hostname: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/overseerr:/config
    networks:
      media_network:
        ipv4_address: 172.20.0.20
    ports:
      - 5055:5055
    restart: unless-stopped

  # Cloudflare Tunnel for Overseerr external access
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      media_network:
        ipv4_address: 172.20.0.21
    restart: unless-stopped
    depends_on:
      - overseerr

  # Stash - Media organizer and manager
  stash:
    image: stashapp/stash:${STASH_VERSION:-latest}
    container_name: stash
    hostname: stash
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      ## Keep configs, scrapers, and plugins here.
      - ${DOCKERCONFDIR}/stash:/root/.stash
      ## Point this at your collection.
      ## The left side is where your collection is on your host, the right side is where it will be in stash.
      - ${DOCKERDATADIR}:/data
      ## This is where your stash's metadata lives
      - ${DOCKERCONFDIR}/stash/metadata:/metadata
      ## Any other cache content.
      - ${DOCKERCONFDIR}/stash/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ${DOCKERCONFDIR}/stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ${DOCKERCONFDIR}/stash/generated:/generated
    networks:
      media_network:
        ipv4_address: 172.20.0.22
    ports:
      - 9999:9999
    restart: unless-stopped

  # Cleanuparr - Cleanup tool for arr apps
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    hostname: cleanuparr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/cleanuparr:/config
      - ${DOCKERDATADIR}:/data
    networks:
      media_network:
        ipv4_address: 172.20.0.23
    ports:
      - 11011:11011
    restart: unless-stopped

  # Huntarr - Torrent tracker manager
  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    hostname: huntarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/huntarr:/config
    networks:
      media_network:
        ipv4_address: 172.20.0.24
    ports:
      - 8088:8088
    restart: unless-stopped
